### PR TITLE
MISC Fixes

### LINKED ISSUE #22: Change logo to butter
The logo still says PopcornTime in the about page.

image

### PR DESCRIPTION
**Pull request by MrAdder**
Added Butter Logo To about page
Removed Popcorn Time Logo

Fixes #22

### CODE REVIEW

File: Gruntfile.js [hunk 1]
```diff
@@ -228,10 +228,10 @@ module.exports = function (grunt) {
 
         exec: {
             win: {
-                cmd: '"build/cache/win/<%= nwjs.options.version %>/nw.exe" .'
+                cmd: '"cache/<%= nwjs.options.version %>/win64/nw.exe" .'
```
Comment (xaiki) [inline Gruntfile.js]: that will break on win32

**Comment by xaiki** [comment]
win64 hardcode will break win32
